spring:
  banner:
    location: banner.txt
  data:
    mongodb:
      host: fintrack-mongodb
      port: 27017
      database: fin_track_db
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG