ktor:
  application:
    modules:
      - br.com.vinilemess.fintrack.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  host: "localhost"
  port: 5432
  database: fintrack_db
  username: $POSTGRES_USERNAME
  password: $POSTGRES_PASS