services:
  fintrack-mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=fintrack_db
#  fintrack-api:
#    container_name: fintrack-api
#    build:
#      context: ./
#      dockerfile: Dockerfile
#      args:
#        SECRET_KEY: ${SECRET_KEY}
#        MONGO_USERNAME: ${MONGODB_USERNAME}
#        MONGO_PASSWORD: ${MONGODB_PASSWORD}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - fintrack-mongodb
