services:
  fintrack-postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=fintrack_db
#  fintrack-api:
#    container_name: fintrack-api
#    build:
#      context: ./
#      dockerfile: Dockerfile
#      args:
#        SECRET_KEY: ${SECRET_KEY}
#        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
#        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - fintrack-postgresql